#CREATE A PRIMARY TABLE 
CREATE TABLE DEP(DEPT_ID NUMERIC(2) PRIMARY KEY,DEPT_NAME VARCHAR(10),FEES_ID NUMERIC(5));

#INSERT VALUES ON DEPARTMENT
INSERT INTO DEP VALUES(1,'CS',38000),(2,'BCA',35000),(3,'B.COM',25000),(4,'BA',20000);

#RETERIVE VALUES
SELECT * FROM DEP;
/*
1	CS	38000
2	BCA	35000
3	B.COM	25000
4	BA	20000
*/

#CREATE A FOREIGN TABLE 
CREATE TABLE STUDENT(NAME VARCHAR(20),DEPT_ID NUMERIC(2), FOREIGN KEY(DEPT_ID) REFERENCES DEP(DEPT_ID) ON DELETE CASCADE,SECTION VARCHAR(2),YEAR NUMERIC(2),FEES_ID NUMERIC(2));
DESC STUDENT;

#DROP A COLUMN
ALTER TABLE STUDENT DROP COLUMN FEES_ID;
DESC STUDENT;

#INSERT VALUES ON DEPARTMENT
INSERT INTO STUDENT VALUES('DHANUSH',1,'A',2),('RAMU',2,'C',1),('ANBU',4,'A',3),('GOBAL',3,'B',NULL);

#RETERIVE VALUES
SELECT * FROM STUDENT;
/*
DHANUSH	1	A	2
RAMU	2	C	1
ANBU	4	A	3
GOBAL	3	B	    
*/

SET SQL_SAFE_UPDATES=0;
#HANDLE NULL VALUES
UPDATE STUDENT SET YEAR='1' WHERE YEAR IS NULL;
SELECT * FROM STUDENT;
/*
DHANUSH	1	A	2
RAMU	2	C	1
ANBU	4	A	3
GOBAL	3	B	1
*/

#DELETE BA RECORDS
DELETE FROM STUDENT WHERE DEPT_ID=4;
SELECT * FROM STUDENT;
/*
DHANUSH	1	A	2
RAMU	2	C	1
GOBAL	3	B	1
*/

#JOIN DEPARTMENT AND STUDENT TABLE
SELECT STUDENT.NAME,DEP.DEPT_NAME,DEP.FEES_ID FROM STUDENT JOIN DEP USING(DEPT_ID);
/*
DHANUSH	CS	38000
RAMU	BCA	35000
GOBAL	B.COM	25000
*/